"""
Django settings for ecommerce project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_admin_logs',
    'myapps.category',
    'myapps.accounts',
    'myapps.store',
    'myapps.carts',
    'myapps.orders',
    'admin_honeypot',
]

INSTALLED_APPS += ('naomi',)

DJANGO_ADMIN_LOGS_DELETABLE = True

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_session_timeout.middleware.SessionTimeoutMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

SESSION_EXPIRE_SECONDS = 33600 #segundos
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True #Que funcione al último momento de inactividad del usuario.
SESSION_TIMEOUT_REDIRECT = '/accounts/login' #Página donde redireccionará luego de cerrar la sesión.

ROOT_URLCONF = 'ecommerce.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'myapps.category.context_processors.menu_links',
                'myapps.carts.context_processors.counter',
            ],
        },
    },
]

WSGI_APPLICATION = 'ecommerce.wsgi.application'

AUTH_USER_MODEL = 'accounts.Account'


# DATABASES = { #Este codigo es sólo una pruba, para conectar mi proyecto a una pase de datos local en Posgrest, lo cual funciona correctamente.
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2', #aquí especifico el motro y que usaré la librería psycopg2 como gestor de base datos.
#         'NAME': 'local_ecommerce', #Nombre de la base de datos que creé en con el PGAdmin de Postgres.
#         'USER': 'postgres', #User name por defecto de Postgres.
#         'PASSWORD': '1I7cJ%9RfZr9XdG9&2', #La contraseña que yo creé al instalar Postgres.
#         'HOST': 'localhost', #Configuraciuón por defecto .
#         'PORT': '5432',#Configuraciuón por defecto .
#     }
# }

heroku_database_url = dj_database_url.config(default=config('DATABASE_URL', None))

if heroku_database_url:
    # heroku production setting
    DATABASES = {
       'default': heroku_database_url
    }
else:
    # development/test setting
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Santo_Domingo'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/' #Esto es un prefijo que se colocará al inicio de la ruta de cada archivo statico
STATIC_ROOT = BASE_DIR /'static' #En esta ruta es donde Dejango extrara y colocará todos mis static file de mis app cuando use el comando: **python manage.py collectstatic**

#if not DEBUG: #Esto evita el error: django The STATICFILES_DIRS setting should not contain the STATIC_ROOT setting
#    STATIC_ROOT =''

STATICFILES_DIRS = [ #En esta lista es le digo a Django, que tengo una carpeta **static** dentro de una app, en este caso es dentro de la carpeta principal del proyecto, si tuviera otras carpetas **static** en otras aplicaciones, las tendría que agregar a esta lista.
    'ecommerce/static'
]

MEDIA_URL = '/static/media/' #Esto es un prefijo que se colocará al inicio de la ruta de cada archivo statico
MEDIA_ROOT = BASE_DIR /'static/media' #Donde se almacenará los archivos Media

#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

#STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

from django.contrib.messages import constants as messages 
MESSAGE_TAGS = {
    messages.ERROR : 'danger', # Aquí indico que el tag error ahora será danger, ya que este último es el que usa bootstrap CSS.
}


if heroku_database_url:
    EMAIL_HOST = config('EMAIL_HOST', default='localhost')
    EMAIL_PORT = config('EMAIL_PORT', default=25, cast=int)
    EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
    EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
else:
    EMAIL_BACKEND = "naomi.mail.backends.naomi.NaomiBackend"
    EMAIL_FILE_PATH = BASE_DIR /"templates/accounts/tmp"


# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
