# Generated by Django 3.2.5 on 2022-03-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_actvite',
            new_name='is_active',
        ),
    ]
